# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rDV1EceVBQpoacWnWM3LKJkYH9Rq5Qwz
"""

import torch
from torchvision import transforms

# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Data configuration
BASE_DIR = "/kaggle/input/chaos-combined-ct-mr-healthy-abdominal-organ/CHAOS_Train_Sets"
BATCH_SIZE = 8
NUM_EPOCHS = 80
TRAIN_RATIO = 0.8
VAL_RATIO = 0.1
TEST_RATIO = 0.1

# Model configuration
BACKBONE_WEIGHTS = "IMAGENET1K_V1"

# Training configuration
LEARNING_RATE = 1e-4
WEIGHT_DECAY = 1e-4
DICE_WEIGHT = 0.5
BOUNDARY_WEIGHT = 0.5

# Transform configuration
data_transform = transforms.Compose([
    transforms.Lambda(lambda x: x.float()),
    transforms.Normalize(mean=[0.5], std=[0.5])
])